# Generated by Django 2.2.16 on 2020-11-11 14:10

from django.db import migrations, models
import timedelta.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloatTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', timedelta.fields.TimedeltaField(max_value=86400.0, min_value=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='IntTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', timedelta.fields.TimedeltaField(max_value=86400.0, min_value=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='MinMaxTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', timedelta.fields.TimedeltaField(min_value=86400.0)),
                ('max', timedelta.fields.TimedeltaField(max_value=86400.0)),
                ('minmax', timedelta.fields.TimedeltaField(max_value=604800.0, min_value=86400.0)),
            ],
        ),
    ]
